import flet as ft
from designer import Designer
from user_data import user_data_class

class profile():
    def __init__(self, page:ft.Page):
        self.page = page
        self.page_view=ft.Column(
            expand=True,
            scroll=ft.ScrollMode.ADAPTIVE,
            controls=[
                ft.Row( #top row
                    controls=[
                        ft.Container(
                            alignment=ft.alignment.center_left,
                            expand=True,
                            #bgcolor="#000000",
                            content=ft.IconButton(on_click=self.go_to_search,hover_color=Designer.colors[0],icon=ft.icons.ARROW_BACK_ROUNDED,icon_size=35, icon_color=Designer.colors[4])
                        ),
                        ft.Container(
                            alignment=ft.alignment.center,
                            expand=True,
                            #bgcolor="#FF0000",
                            content=ft.Text(value="Account",size=26, color=Designer.colors[4])
                        ),
                        ft.Container(
                            alignment=ft.alignment.center_right,
                            expand=True,
                            #bgcolor="#1529DD",
                            content=ft.IconButton(on_click=self.go_to_seting,hover_color=Designer.colors[0],icon=ft.icons.SETTINGS_ROUNDED,icon_size=35, icon_color=Designer.colors[4])
                        ),
                    ]
                ),
                ft.Row(#prof data
                    controls=[
                        ft.Container(
                            bgcolor=Designer.colors[3],
                            expand=True,
                            padding=ft.padding.all(15),
                            content=ft.Column(
                                controls=[
                                    ft.Row(
                                        controls=[
                                            ft.CircleAvatar(
                                                content=ft.Icon(ft.icons.ABC),
                                            ),
                                        ]
                                    ),
                                    ft.Row(
                                        controls=[
                                            ft.Text(
                                                value="name:",
                                                color=Designer.colors[4],
                                                size=22,
                                            ),
                                            ft.Text(
                                                value=user_data_class.name,
                                                color=Designer.colors[4],
                                                size=22,
                                            ),
                                        ]    
                                    ),
                                    ft.Row(
                                        controls=[
                                            ft.Text(
                                                value="role:",
                                                color=Designer.colors[4],
                                                size=22,
                                            ),
                                            ft.Text(
                                                value=user_data_class.role,
                                                color=Designer.colors[4],
                                                size=22,
                                            ),
                                        ]    
                                    ),
                                    ft.Row(
                                        controls=[
                                            ft.Text(
                                                value="Phone number:",
                                                color=Designer.colors[4],
                                                size=22,
                                            ),
                                            ft.Text(
                                                value=user_data_class.phone_number,
                                                color=Designer.colors[4],
                                                size=22,
                                            ),
                                        ]
                                    ),
                                    ft.Row(
                                        controls=[
                                            ft.Text(
                                                value=user_data_class.rating,
                                                color=Designer.colors[4],
                                                size=22,
                                            ),
                                            ft.Icon(
                                                name=ft.icons.STAR_ROUNDED,
                                                size=30,
                                                color=Designer.colors[0]
                                            )
                                        ]
                                    ),
                                ]    
                            ),
                        )
                    ]
                ),
                ft.Row(
                    controls=[
                        ft.Container(#orders container
                            bgcolor=Designer.colors[3],
                            expand=True,
                            on_click=self.go_to_my_orders,
                            padding=ft.padding.all(15),
                            content=ft.Column(
                                controls=[
                                    ft.Row(
                                        controls=[
                                            ft.Text(
                                                value="Orders",
                                                size=22,
                                                color=Designer.colors[4]
                                            ),
                                        ]
                                    ),
                                    ft.Row(
                                        controls=[
                                            ft.Icon(
                                                name=ft.icons.EDIT_DOCUMENT,
                                                size=50,
                                                color=Designer.colors[4],
                                            ),
                                            ft.Text(
                                                value="You orders:",
                                                size=22,
                                                color=Designer.colors[4]
                                            ),
                                            ft.Text(
                                                value=user_data_class.count_orders,
                                                size=22,
                                                color=Designer.colors[4]
                                            ),
                                        ]    
                                    ),
                                ]
                            )
                        )
                    ]
                ),
                ft.Row(
                    controls=[
                        ft.Container(#adres container
                            bgcolor=Designer.colors[3],
                            expand=True,
                            padding=ft.padding.all(15),
                            content=ft.Column(
                                controls=[
                                    ft.Row(
                                        controls=[
                                            ft.Text(
                                                value="Address:",
                                                size=22,
                                                color=Designer.colors[4]
                                            ),
                                        ]
                                    ),
                                    ft.Row(
                                        controls=[
                                            ft.Icon(
                                                name=ft.icons.HOME_ROUNDED,
                                                size=50,
                                                color=Designer.colors[4],
                                            ),
                                            ft.Text(
                                                value="You address:",
                                                size=22,
                                                color=Designer.colors[4]
                                            ),
                                            ft.Text(
                                                value=user_data_class.address,
                                                size=22,
                                                color=Designer.colors[4]
                                            ),
                                        ]    
                                    ),
                                ]
                            )
                        )
                    ]
                ),
                ft.Row(
                    controls=[
                        ft.Container(#mail container
                            bgcolor=Designer.colors[3],
                            expand=True,
                            padding=ft.padding.all(15),
                            content=ft.Column(
                                controls=[
                                    ft.Row(
                                        controls=[
                                            ft.Text(
                                                value="E-mail:",
                                                size=22,
                                                color=Designer.colors[4]
                                            ),
                                        ]
                                    ),
                                    ft.Row(
                                        controls=[
                                            ft.Icon(
                                                name=ft.icons.ALTERNATE_EMAIL_ROUNDED,
                                                size=50,
                                                color=Designer.colors[4],
                                            ),
                                            ft.Text(
                                                value="You E-mail:",
                                                size=22,
                                                color=Designer.colors[4]
                                            ),
                                            ft.Text(
                                                value=user_data_class.email,
                                                size=22,
                                                color=Designer.colors[4]
                                            ),
                                        ]    
                                    ),
                                ]
                            )
                        )
                    ]
                ),
                ft.Row(
                    controls=[
                        ft.Container(
                            expand=True,
                            height=50,
                            alignment=ft.alignment.center,
                            bgcolor=Designer.colors[0],
                            content=ft.Text(value="Exit", size=22,color=Designer.colors[4])
                        )
                    ]
                )
            ]
        )
    def go_to_my_orders(self,e):
        self.page.go("/my_orders")
    def go_to_search(self,e):
        self.page.go("/search")
    def go_to_seting(self,e):
        self.page.go("/seting")